# Generated by Django 4.2.1 on 2025-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci_app', '0007_alter_smlouvy_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_pojistence', models.CharField(max_length=40, null=True)),
                ('nazev_pojisteni', models.CharField(max_length=40, null=True)),
                ('detail_akce', models.CharField(max_length=200, null=True)),
                ('datum_cas', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Smluvní události',
            },
        ),
        migrations.DeleteModel(
            name='SmluvniUdalosti',
        ),
    ]
