# Generated by Django 4.2.1 on 2025-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci_app', '0008_historie_delete_smluvniudalosti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historie',
            options={'verbose_name_plural': 'Historie událostí'},
        ),
        migrations.RenameField(
            model_name='historie',
            old_name='jmeno_pojistence',
            new_name='pojistenec',
        ),
        migrations.RenameField(
            model_name='historie',
            old_name='nazev_pojisteni',
            new_name='produkt',
        ),
        migrations.AddField(
            model_name='historie',
            name='pojistenec_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historie',
            name='produkt_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historie',
            name='smlouva_id',
            field=models.IntegerField(null=True),
        ),
    ]
