# Generated by Django 4.2.1 on 2025-02-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzivatele',
            new_name='Pojistenci',
        ),
    ]
