# Generated by Django 4.2.1 on 2025-02-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0004_produkty_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmluvniUdalosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_pojistence', models.CharField(max_length=40)),
                ('nazev_pojisteni', models.CharField(max_length=40)),
                ('je_vznik', models.BooleanField(
                    verbose_name='Vznik smlouvy (TRUE), Zánik smlouva (FALSE)')),
                ('castka_kryti', models.IntegerField(verbose_name='Částka krytí')),
                ('cena', models.FloatField(verbose_name='Cena')),
                ('datum', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Smluvní události',
            },
        ),
        migrations.AlterModelOptions(
            name='pojistenci',
            options={'verbose_name': 'Pojištěnec',
                     'verbose_name_plural': 'Pojištěnci'},
        ),
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt',
                     'verbose_name_plural': 'Produkty'},
        ),
        migrations.CreateModel(
            name='Smlouvy',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('castka_kryti', models.IntegerField(verbose_name='Částka krytí')),
                ('cena', models.FloatField(verbose_name='Cena')),
                ('datum', models.DateField()),
                ('pojistenec_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='safehouse_app.pojistenci')),
                ('produkt_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='safehouse_app.produkty')),
            ],
            options={
                'verbose_name_plural': 'Smlouvy',
            },
        ),
    ]
