# Generated by Django 4.2.1 on 2025-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0005_smluvniudalosti_alter_pojistenci_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenci',
            name='je_muz',
            field=models.BooleanField(default=True),
        ),
    ]
