# Generated by Django 4.2.1 on 2025-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0006_pojistenci_je_muz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smlouvy',
            name='datum',
            field=models.DateField(auto_now=True),
        ),
    ]
