# Generated by Django 4.2.1 on 2025-03-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0010_historie_akce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pojistenci',
            new_name='Klienti',
        ),
        migrations.AlterModelOptions(
            name='klienti',
            options={'verbose_name': 'Klient',
                     'verbose_name_plural': 'Klienti'},
        ),
        migrations.RenameField(
            model_name='historie',
            old_name='pojistenec_id',
            new_name='klient_id',
        ),
        migrations.RenameField(
            model_name='historie',
            old_name='pojistenec',
            new_name='klient_str',
        ),
        migrations.RenameField(
            model_name='historie',
            old_name='produkt',
            new_name='produkt_str',
        ),
        migrations.RenameField(
            model_name='smlouvy',
            old_name='pojistenec_id',
            new_name='klient_id',
        ),
        migrations.AlterField(
            model_name='produkty',
            name='nazev',
            field=models.CharField(
                max_length=80, verbose_name='Název produktu'),
        ),
    ]
