# Generated by Django 4.2.1 on 2025-03-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safehouse_app', '0011_rename_pojistenci_klienti_alter_klienti_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smlouvy',
            old_name='klient_id',
            new_name='klient',
        ),
        migrations.RenameField(
            model_name='smlouvy',
            old_name='produkt_id',
            new_name='produkt',
        ),
    ]
